### ISSUE TITLE
Draft ROpenSci Checklist

### ISSUE THREAD

**Issue by akoontz11** [pearselab/SymbiotaR2#7]
Below is the demo ROpenSci issue list. Let me know what looks incorrect. The 3 items I'm unsure on are:
1. Package categories, 
2. The technical checkbox for continuous integration (CI)? We didn't reference the `usethis` package at all, or Travis--but my understanding in this area is limited. 
3. Confirmation that we intend for this package to go onto CRAN afterwards? I ask because the [testing section on the ROpenSci dev guide](https://devguide.ropensci.org/building.html#testing) talks about a `skip_on_cran()` command that we'll seem to need if we are to submit there...

---

Submitting Author: Austin Koontz (@akoontz11 )  
Repository: https://github.com/pearselab/SymbiotaR2
Version submitted: 0.0.1
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: SymbiotaR2
Type: Package
Title: Downloading data from Symbiota2 portals into R
Version: 0.0-1
Authors@R: c(person("Austin", "Koontz", email = "austin.koontz@usu.edu", role = c("aut", "cre")),
    person("William D.", "Pearse", email = "will.pearse@gmail.com", role ="aut", comment=c(ORCID="0000-0002-6241-3164")))
Maintainer: Austin Koontz <austin.koontz@usu.edu>
Description: Download data from Symbiota2 portals using Symbiota's
    API. Covers the Checklists, Collections, Crowdsource, Exsiccati,
    Glossary, ImageProcessor, Key, Media, Occurrence, Reference, Taxa,
    Traits, and UserRoles API families. Each Symbiota2 portal owner
    can load their own plugins (and modified code), and so this
    package may not cover every possible API endpoint from a given
    Symbiota2 instance.
License: MIT + file LICENSE
URL: https://github.com/pearselab/SymbiotaR2
BugReports: https://github.com/pearselab/SymbiotaR2/issues
VignetteBuilder: knitr
LazyLoad: yes
Suggests:
    knitr (>= 1.23),
    testthat (>= 2.0.0),
    vcr (>= 0.3.0)	
Imports:
    httr (>= 1.0.0),
    xml2 (>= 1.2.0),
    rjson (>= 0.2.20),
    fs (>= 1.2.6)
Encoding: UTF-8
RoxygenNote: 7.0.2
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [x] data retrieval
	- [ ] data extraction
	- [x] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automataion
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [x] scientific software wrappers
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis
	
- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

The primary purpose of SymbiotaR2 is to allow users to pull objects from the specified Symbiota2 database portal into an R environment. It does this by wrapping each of the default API calls made available on the Symbiota2 portal of interest.

-   Who is the target audience and what are scientific applications of this package?  

The target audiences includes anyone interested in using R to analyze biological specimen data made available through the Symbiota2 content management system. Potential scientific applications include comparing biological trait data between different lineages, analyzing phenological data, and biodiversity research generally.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No R packages have been developed for the [updated code structure provided by Symbiota2](http://symbiota.org/docs/project-summary/).

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [x] includes [documentation with examples for all functions](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?  
- [x] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [x] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
    - [x] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)  
  
</details>

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [ ] The package is novel and will be of interest to the broad readership of the journal. 
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by willpearse** [comment]
I've added "data retrieval" to the categories. We will have Travis-CI (running now, although it will fail because not all the tests work). Once that's up and running, I'll setup Coveralls. I'll show you how I do that once it's done; it's fiddly... We don't need to worry about the `skip_on_cran` stuff because we're using `vcr` to circumvent that.

**Comment by akoontz11** [comment]
Closing this issue, as official ROpenSci Checklist exists.
